### PR TITLE
Add Plotly scripts to generate wastewater data visualisations

### PR DESCRIPTION
**Pull request by Ziip-dev**
Add `covid_umea.py` and `covid_orebro.py` to produce wastewater visualisation with Plotly.

We use the data file provided on blobserver as input and generate a plotly `json` file  that is stored on blobserver as well.

### CODE REVIEW

**Review by LianeHughes — COMMENTED** [review]
Need to determine whether changes to openpyxl version would have impact on the other plots in this subfolder to ensure that it has no impact during dynamic update. It does not seem likely, but would be good to discuss the reasons for the upgrade.

**Comment by Ziip-dev** [comment]
They are following semver and it's a minor version change so it should not.
If I recall correctly it was because of a conflicting version requirement with python... but I may double check as well :)

**Comment by Ziip-dev** [comment]
`openpyxl` all clear :)
Are we waiting for the research group's input regarding the three stars '***' before merging?

**Comment by Ziip-dev** [comment]
To sum things up:

- [x] global visualisation responsiveness to True
- [x] visualisation <div> CSS style to 600px so it stops shrinking and becomes scroll-able on smaller view-ports
- [x] hover data improved
- [x] pages content updated according to your commits

**Review by LianeHughes — APPROVED** [review]

**Pull request merged**
